.TH "allele" 3 "Sun Jul 29 2018" "iVar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
allele
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBallele\fP &a) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBallele\fP &a) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBnuc\fP"
.br
.ti -1c
.RI "uint32_t \fBdepth\fP"
.br
.ti -1c
.RI "uint32_t \fBreverse\fP"
.br
.ti -1c
.RI "uint8_t \fBmean_qual\fP"
.br
.ti -1c
.RI "uint32_t \fBbeg\fP"
.br
.ti -1c
.RI "uint32_t \fBend\fP"
.br
.ti -1c
.RI "float \fBtmp_mean_qual\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for iVar from the source code\&.
