.TH "args_t" 3 "Sun Jul 29 2018" "iVar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
args_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBbam\fP"
.br
.ti -1c
.RI "std::string \fBbed\fP"
.br
.ti -1c
.RI "std::string \fBprefix\fP"
.br
.ti -1c
.RI "std::string \fBref\fP"
.br
.ti -1c
.RI "std::string \fBregion\fP"
.br
.ti -1c
.RI "uint8_t \fBmin_qual\fP"
.br
.ti -1c
.RI "uint8_t \fBsliding_window\fP"
.br
.ti -1c
.RI "double \fBmin_threshold\fP"
.br
.ti -1c
.RI "int \fBmin_length\fP"
.br
.ti -1c
.RI "std::string \fBf1\fP"
.br
.ti -1c
.RI "std::string \fBf2\fP"
.br
.ti -1c
.RI "std::string \fBadp_path\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for iVar from the source code\&.
