.TH "cookbookpage" 3 "Fri Aug 3 2018" "iVar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cookbookpage \- Cookbook 

.PP
.PP
.nf
Call iSNVs from samples with unknown reference sequence
----

<img src="https://raw\&.githubusercontent\&.com/gkarthik/IVAR/master/pipeline_field/pipeline_field\&.png" width="500" />
.fi
.PP
.PP
``` 
