.TH "installpage" 3 "Fri Aug 10 2018" "iVar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
installpage \- Installation 

.SS "Dependencies"
.PP
.IP "\(bu" 2
\fChtslib\fP
.IP "\(bu" 2
\fCAwk\fP - Pre-installed on most UNIX systems\&.
.PP
.PP
Note:
.IP "\(bu" 2
It is highly recommended that \fCsamtools\fP also be installed alongside iVar\&. iVar uses the output of samtools mpileup to call variants and generate consensus sequences\&. In addition, samtools \fCsort\fP and \fCindex\fP commands are very useful to setup a pipeline using iVar\&.
.PP
.PP
.SS "Installing on Mac"
.PP
\fCXcode\fP from Apple is required to compile iVar (and other tools) from source\&. If you don't want to install the full Xcode package from the AppStore, you can install the Xcode command line tools,
.PP
.PP
.nf
xcode-select --install
.fi
.PP
.PP
\fCGNU Autotools\fP is required to compile iVar from source\&.
.PP
To install Autotools using \fChomebrew\fP please use the command below,
.PP
.PP
.nf
brew install autoconf automake libtool
.fi
.PP
.PP
To install iVar, run the following commands\&.
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure
make
make install
.fi
.PP
.PP
If htslib has been installed in a non standard location, please run the following commands,
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure --with-hts=/prefix/to/bin/folder/with/htslib
make
make install
.fi
.PP
.PP
If htslib is installed in a non standard location, please add the following to your \&.bash_profile so that iVar can find htslib dynamic libraries during runtime\&.
.PP
.PP
.nf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/hts/lib/folder
.fi
.PP
.PP
To test installation just run, \fCivar version\fP and you should get the following output,
.PP
.PP
.nf
iVar version 1\&.0

Please raise issues and bug reports at https://github\&.com/andersen-lab/ivar/
.fi
.PP
.PP
.SS "Installing on Linux"
.PP
\fCGNU Autotools\fP is required to compile iVar from source\&.
.PP
To install Autotools using \fCAPT\fP please use the command below,
.PP
.PP
.nf
apt-get install autotools-dev
.fi
.PP
.PP
To install iVar, run the following commands\&.
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure
make
make install
.fi
.PP
.PP
If htslib has been installed in a non standard location, please run,
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure --with-hts=/prefix/to/bin/folder/with/htslib
make
make install
.fi
.PP
.PP
If htslib is installed in a non standard location, please add the following to your \&.bashrc so that iVar can find htslib dynamic libraries during runtime\&.
.PP
.PP
.nf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/hts/lib/folder
.fi
.PP
.PP
To test installation just run, \fCivar version\fP and you should get the following output,
.PP
.PP
.nf
iVar version 1\&.0

Please raise issues and bug reports at https://github\&.com/andersen-lab/ivar/
.fi
.PP
.PP
.SS "Contact"
.PP
For bug reports please email gkarthik[at]scripps\&.edu or raise an issue on Github\&. 
