.TH "installpage" 3 "Tue Nov 6 2018" "iVar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
installpage \- Installation 

.SS "Dependencies"
.PP
.IP "\(bu" 2
\fCHTSlib\fP
.IP "\(bu" 2
\fCAwk\fP - Pre-installed on most UNIX systems\&.
.IP "\(bu" 2
\fCGCC\fP any version after v5\&.0\&. Support for c++11 standard required\&.
.PP
.PP
Note:
.IP "\(bu" 2
It is highly recommended that \fCsamtools\fP also be installed alongside iVar\&. iVar uses the output of samtools mpileup to call variants and generate consensus sequences\&. In addition, samtools \fCsort\fP and \fCindex\fP commands are very useful to setup a pipeline using iVar\&.
.PP
.SH "Installing on Mac"
.PP
.SS "Installing build tools"
\fCXcode\fP from Apple is required to compile iVar (and other tools) from source\&. If you don't want to install the full Xcode package from the AppStore, you can install the Xcode command line tools,
.PP
.PP
.nf
xcode-select --install
.fi
.PP
.PP
\fCGNU Autotools\fP is required to compile iVar from source\&.
.PP
To install Autotools using \fChomebrew\fP please use the command below,
.PP
.PP
.nf
brew install autoconf automake libtool
.fi
.PP
.SS "HTSlib installed using conda"
HTSlib can be installed with \fCconda\fP using the command,
.PP
.PP
.nf
conda install -c bioconda htslib
.fi
.PP
.PP
The conda binary is by default installed at /opt/\&. You can check the installation location by running the following command,
.PP
.PP
.nf
which conda
.fi
.PP
.PP
The output of the command will be in this format - /opt/conda/bin/conda or /opt/anaconda2/bin/conda or /opt/anaconda3/bin/conda depending on whether you installed miniconda or anaconda\&.
.PP
If the output is for example, /opt/conda/bin/conda, then you can add the path to the lib folder to $LD_LIBRARY_PATH using the command below\&. You can add this to your ~/\&.bash_profile or ~/\&.bashrc to avoid rerunning the command everytime a new bash session starts\&.
.PP
.PP
.nf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/conda/lib
.fi
.PP
.SS "HTSlib installed from source"
Installation instructions and downloads for HTSlib can be found at http://www.htslib.org/download/\&.
.PP
If HTSlib is installed in a non standard location, please add the following to your \&.bash_profile so that iVar can find HTSlib dynamic libraries during runtime\&.
.PP
.PP
.nf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/hts/lib/folder
.fi
.PP
.SS "Installing iVar"
To install iVar, run the following commands\&.
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure
make
make install
.fi
.PP
.PP
If HTSlib was installed using conda, please run the following commands by supplying the prefix to the bin folder of the conda binary\&.
.PP
The prefix to the bin folder can be found using the command \fCwhich conda\fP\&. The output of the command will be in this format - /opt/conda/bin/conda or /opt/anaconda2/bin/conda or /opt/anaconda3/bin/conda depending on whether you installed miniconda or anaconda\&. For example, if the output of the command is /opt/conda/bin/conda, the prefix to the htslib bin folder will be /opt/conda\&. This can be supplied to \&./configure --with-hts=/opt/conda\&.
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure --with-hts=/prefix/to/bin/folder/with/HTSlib
make
make install
.fi
.PP
.PP
If HTSlib was installed in a non standard location, please run the following commands,
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure --with-hts=/prefix/to/bin/folder/with/HTSlib
make
make install
.fi
.PP
.PP
To test installation just run, \fCivar version\fP and you should get the following output,
.PP
.PP
.nf
iVar version 1\&.0

Please raise issues and bug reports at https://github\&.com/andersen-lab/ivar/
.fi
.PP
.SH "Installing on Linux"
.PP
.SS "Installing build tools"
\fCGNU Autotools\fP is required to compile iVar from source\&.
.PP
To install Autotools using \fCAPT\fP please use the command below,
.PP
.PP
.nf
apt-get install autotools-dev
.fi
.PP
.SS "HTSlib installed using conda"
HTSlib can be installed with \fCconda\fP using the command,
.PP
.PP
.nf
conda install -c bioconda htslib
.fi
.PP
.PP
The conda binary is by default installed at /opt/\&. You can check the installation location by running the following command,
.PP
.PP
.nf
which conda
.fi
.PP
.PP
The output of the command will be in this format - /opt/conda/bin/conda or /opt/anaconda2/bin/conda or /opt/anaconda3/bin/conda depending on whether you installed miniconda or anaconda\&.
.PP
If the output is for example, /opt/conda/bin/conda, then you can add the path to the lib folder to $LD_LIBRARY_PATH using the command below\&. You can add this to your ~/\&.bash_profile or ~/\&.bashrc to avoid rerunning the command everytime a new bash session starts\&.
.PP
.PP
.nf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/conda/lib
.fi
.PP
.SS "HTSlib installed from source"
Installation instructions and downloads for HTSlib can be found at http://www.htslib.org/download/\&.
.PP
If HTSlib is installed in a non standard location, please add the following to your \&.bash_profile so that iVar can find HTSlib dynamic libraries during runtime\&.
.PP
.PP
.nf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/hts/lib/folder
.fi
.PP
.SS "Installing iVar"
To install iVar, run the following commands\&.
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure
make
make install
.fi
.PP
.PP
If HTSlib was installed using conda, please run the following commands by supplying the prefix to the bin folder of the conda binary\&.
.PP
The prefix to the bin folder can be found using the command \fCwhich conda\fP\&. The output of the command will be in this format - /opt/conda/bin/conda or /opt/anaconda2/bin/conda or /opt/anaconda3/bin/conda depending on whether you installed miniconda or anaconda\&. For example, if the output of the command is /opt/conda/bin/conda, the prefix to the htslib bin folder will be /opt/conda\&. This can be supplied to \&./configure --with-hts=/opt/conda\&.
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure --with-hts=/prefix/to/bin/folder/with/HTSlib
make
make install
.fi
.PP
.PP
If HTSlib was installed in a non standard location, please run the following commands,
.PP
.PP
.nf
\&./autogen\&.sh
\&./configure --with-hts=/prefix/to/bin/folder/with/HTSlib
make
make install
.fi
.PP
.PP
To test installation just run, \fCivar version\fP and you should get the following output,
.PP
.PP
.nf
iVar version 1\&.0

Please raise issues and bug reports at https://github\&.com/andersen-lab/ivar/
.fi
.PP
.SH "Running from Docker"
.PP
iVar can also be run via \fCDocker\fP\&. Pull the docker image from \fCDocker Hub\fP using the following command,
.PP
.PP
.nf
docker pull andersenlabapps/ivar
.fi
.PP
.PP
This docker image contains all the required dependencies to run iVar and the \fBpipelines\fP developed using iVar\&. You will have to attach a docker volume to get data into the docker container\&. Instructions to do so are in the \fCDocker docs\fP\&.
.PP
\fCiVar on Docker Hub\fP
.SH "Contact"
.PP
For bug reports please email gkarthik[at]scripps\&.edu or raise an issue on Github\&. 
