.TH "primer" 3 "Sun Jul 29 2018" "iVar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
primer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBget_name\fP ()"
.br
.ti -1c
.RI "std::string \fBget_region\fP ()"
.br
.ti -1c
.RI "int \fBget_score\fP ()"
.br
.ti -1c
.RI "unsigned int \fBget_start\fP ()"
.br
.ti -1c
.RI "unsigned int \fBget_end\fP ()"
.br
.ti -1c
.RI "char \fBget_strand\fP ()"
.br
.ti -1c
.RI "int \fBget_length\fP ()"
.br
.ti -1c
.RI "void \fBset_start\fP (unsigned int s)"
.br
.ti -1c
.RI "void \fBset_end\fP (unsigned int e)"
.br
.ti -1c
.RI "void \fBset_strand\fP (char s)"
.br
.ti -1c
.RI "void \fBset_region\fP (std::string r)"
.br
.ti -1c
.RI "void \fBset_name\fP (std::string n)"
.br
.ti -1c
.RI "void \fBset_score\fP (int s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for iVar from the source code\&.
