.TH "ret_t" 3 "Sun Jul 29 2018" "iVar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ret_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBnuc\fP"
.br
.ti -1c
.RI "std::string \fBq\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for iVar from the source code\&.
