name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@master
    - name: download htslib
      run: wget https://github.com/samtools/htslib/archive/1.10.2.tar.gz
    - name: untar
      run: tar xf 1.10.2.tar.gz
    - name: install htslib
      env:
        CC: gcc-7
      run: |
        cd htslib-1.10.2/
        autoheader
        autoconf
        ./configure
        make
        sudo make install
        sudo ldconfig
    - name: autotools
      env:
        CC: gcc-7
      run: ./autogen.sh
    - name: configure
      env:
        CC: gcc-7
      run: ./configure
    - name: make
      env:
        CC: gcc-7
      run: make
    - name: make check
      env:
        CC: gcc-7
      run: make check
    - name: make install
      env:
        CC: gcc-7
      run: sudo make install

  build-macos:

    runs-on: [ macos-latest ]

    steps:
    - uses: actions/checkout@master
    - name: install GNU autotools
      run: brew install autoconf automake libtool
    - name: download htslib
      run: wget https://github.com/samtools/htslib/archive/1.10.2.tar.gz
    - name: untar
      run: tar xf 1.10.2.tar.gz
    - name: install htslib
      run: |
        cd htslib-1.10.2/
        autoheader
        autoconf
        ./configure
        make
        sudo make install
    - name: autoconf
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
